### ISSUE TITLE
BiRNN in the spectral filtering layer?

### ISSUE THREAD

**Issue by ZhuangweiKang** [ahmedmalaa/Fourier-flows#3]
Thank you for publishing the repository. I noticed that you commented the RNN layer in the bijectors of spectral flow. Did they lead to poor performance? Or any other reason to do so? Thank you!

**Comment by ahmedmalaa** [comment]
Hi ZhuangweiKang, No, they will generally perform better at the expense of compute time since we cascade multiple flows each with its RNN layer. I recommend uncommenting the RNN layer if you are running the model on GPU.

**Comment by ZhuangweiKang** [comment]
Thanks for your quick response. Also, does BiRNN and RNN have different performance? And does the different masking rule influence performance (such as [0,1,0,1,...] and [0,0,0,...,1,1,1])?

**Comment by ahmedmalaa** [comment]
I did not find them to have diff performance on simple 1D time series. The masks are introduced to handle variable length sequences and are not arbitrary, they have to take the form [1, 1, 1, 1, 0, 0, ..., 0].

**Comment by ZhuangweiKang** [comment]
I see. Thank you very much.

**Comment by ZhuangweiKang** [comment]
Hello, can this approach handle multi-variate time series? I noticed the real_data_loading function selects one column from the energy and stock datasets.
